version: "3.8"

services:
  crawler:
    build: ./crawler
    volumes:
      - type: bind
        source: ./data/
        target: /data/
    environment:
      CONFIG_PATH: /data/config.yml
      NODE_ENV: development
      TZ: Asia/Tokyo
    depends_on:
      mariadb:
        condition: service_healthy
    init: true
    restart: always

  web:
    build: ./web
    volumes:
      - type: bind
        source: ./data/
        target: /data/
    ports:
      - 8080:8080
    environment:
      CONFIG_PATH: /data/config.yml
      NODE_ENV: development
      TZ: Asia/Tokyo
    depends_on:
      mariadb:
        condition: service_healthy
    init: true
    restart: always

  mariadb:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: rootPassword
      MYSQL_USER: watcher
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: watch-twitter-likes
      TZ: Asia/Tokyo
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - "./db-data:/var/lib/mysql"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: rootPassword
      TZ: Asia/Tokyo
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - 8000:80
    volumes:
      - /sessions
